import type { Locale } from "./index";

export const chatSuggestions: Record<Locale, string[]> = {
  en: ["What is Zainal's current role?", "What does Zainal do at DDL?", "How did he contribute to Project Bersama?", "What technical skills does he use?"],
  id: ["Apa peran Zainal saat ini?", "Apa yang dikerjakan di DDL?", "Apa kontribusinya di Project Bersama?", "Skill teknis apa yang digunakan?"],
  jv: ["Apa perane Zainal saiki?", "Apa sing digarap ing DDL?", "Apa kontribusine ing Project Bersama?", "Skill teknis apa sing dienggo?"],
};

const replies = {
  empty: ["Please ask a question about Zainal's work, projects, skills, or contact details.", "Silakan tulis pertanyaan tentang Zainal Abidin. Contoh: peran saat ini, pengalaman kerja, kontribusi di proyek, skill, atau kontak.", "Tulisen pitakon babagan Zainal Abidin. Contone: perane saiki, pengalaman kerja, kontribusi ing proyek, skill, utawa kontak."],
  greeting: ["Hi! I can answer questions about Zainal Abidin, Technical Product Specialist at Indivara Group, with a background in software and data engineering. Ask about product work, projects, client implementation, skills, CV, or contact details.", "Halo! Aku bisa menjawab pertanyaan tentang Zainal Abidin, Technical Product Specialist di Indivara Group dengan latar software dan data engineering. Tanyakan tentang pengalaman produk, proyek, implementasi klien, skill, CV, atau kontaknya.", "Halo! Aku bisa mangsuli pitakon babagan Zainal Abidin, Technical Product Specialist ing Indivara Group kanthi latar software lan data engineering. Takona babagan pekerjaan produk, proyek, implementasi klien, skill, CV, utawa kontak."],
  data: ["Zainal works as a Technical Product Specialist and contributes to data solutions: cleaning and standardization, SQL/Python transformations, and delivery through APIs and dashboards. In Project Bersama, his contribution involved a pipeline with 1.7M+ source records and 6.4M+ analytics output rows. See the Data page for illustrative workflows.", "Zainal saat ini bekerja sebagai Technical Product Specialist dan berkontribusi pada solusi data: pembersihan serta standardisasi data, transformasi SQL/Python, dan penyajian melalui API serta dashboard. Di Project Bersama, kontribusinya mencakup pipeline dengan 1,7 juta+ record sumber dan 6,4 juta+ baris keluaran analitik. Lihat halaman Data untuk contoh workflow dan transformasi.", "Zainal saiki kerja minangka Technical Product Specialist lan melu nggarap solusi data: ngresiki lan nyeragamake data, transformasi SQL/Python, lan nyedhiyakake liwat API lan dashboard. Ing Project Bersama, kontribusine ana ing pipeline kanthi 1,7 yuta+ record sumber lan 6,4 yuta+ baris keluaran analitik. Deleng kaca Data kanggo tuladha workflow."],
  profile: ["Zainal Abidin is a Technical Product Specialist at Indivara Group. Starting in frontend engineering with React, TypeScript and Next.js, he now connects product delivery, data solutions, client implementation and engineering. He is based in East Java, Indonesia.", "Zainal Abidin adalah Technical Product Specialist di Indivara Group. Berawal dari frontend engineering dengan React, TypeScript, dan Next.js, kini ia menghubungkan product delivery, solusi data, implementasi klien, dan engineering. Ia berbasis di Jawa Timur, Indonesia.", "Zainal Abidin minangka Technical Product Specialist ing Indivara Group. Wiwit saka frontend engineering nganggo React, TypeScript, lan Next.js, saiki dheweke nyambungake pangiriman produk, solusi data, implementasi klien, lan engineering. Dheweke manggon ing Jawa Timur, Indonesia."],
  experience: ["Since January 2026, Zainal has worked as a Technical Product Specialist at Indivara Group after Delman joined Indivara. He supports DDL, Bersama's data and dashboard work, and client implementations. Previously he worked at Delman as a Frontend Engineer (full-time, contract and internship), as well as in freelance roles and an internship at Ninja Van.", "Sejak Januari 2026, Zainal bekerja sebagai Technical Product Specialist di Indivara Group setelah Delman bergabung dengan Indivara. Ia membantu kesinambungan produk DDL, proyek data dan dashboard Bersama, serta implementasi klien. Sebelumnya ia bekerja di Delman sebagai Frontend Engineer (full-time, kontrak, dan magang), serta memiliki pengalaman freelance dan magang di Ninja Van.", "Wiwit Januari 2026, Zainal kerja minangka Technical Product Specialist ing Indivara Group sawisé Delman gabung karo Indivara. Dheweke mbantu DDL, proyek data lan dashboard Bersama, lan implementasi klien. Sadurunge dheweke kerja ing Delman minangka Frontend Engineer (full-time, kontrak, lan magang), uga duwe pengalaman freelance lan magang ing Ninja Van."],
  skills: ["Relevant skills include Python, SQL, PostgreSQL, REST APIs, data cleaning and standardization, React, Next.js, TypeScript, Docker and Linux/VM deployment. He also works on requirements analysis, stakeholder coordination, client implementation and UAT.", "Skill yang paling relevan dengan pekerjaannya mencakup Python, SQL, PostgreSQL, REST API, pembersihan dan standardisasi data, React, Next.js, TypeScript, Docker, serta deployment Linux/VM. Ia juga bekerja dengan analisis kebutuhan, koordinasi stakeholder, implementasi klien, dan UAT.", "Skill sing cocog karo pekerjaane kalebu Python, SQL, PostgreSQL, REST API, ngresiki lan nyeragamake data, React, Next.js, TypeScript, Docker, lan deployment Linux/VM. Dheweke uga nggarap analisis kabutuhan, koordinasi pihak terkait, implementasi klien, lan UAT."],
  projects: ["Zainal's work includes developing and deploying Delman Data Lab, data solutions and dashboards for Project Bersama, API optimization for Bersama and SamaSamaApps Philippines, and a Seedbox email-notification demo for UAT. See Projects and Data for more detail.", "Pilihan pekerjaan Zainal meliputi pengembangan dan deployment Delman Data Lab, solusi data dan dashboard Project Bersama, optimasi API untuk Bersama dan SamaSamaApps Philippines, serta demo notifikasi email Seedbox untuk persiapan UAT. Buka menu Projects dan Data untuk ringkasan lebih lanjut.", "Pekerjaane Zainal kalebu ngembangake lan nindakake deployment Delman Data Lab, solusi data lan dashboard Project Bersama, optimasi API kanggo Bersama lan SamaSamaApps Philippines, lan demo notifikasi email Seedbox kanggo UAT. Deleng Proyek lan Data kanggo rincian liyane."],
  community: ["Zainal was part of Gatherloop's core team and helped coordinate the Probolinggo frontend community, which has 145+ members, including supporting monthly tech talks.", "Zainal menjadi bagian dari core team Gatherloop dan membantu mengoordinasikan komunitas frontend Probolinggo yang beranggotakan 145+ orang, termasuk mendukung tech talk bulanan.", "Zainal dadi anggota core team Gatherloop lan mbantu ngoordinasi komunitas frontend Probolinggo sing nduwe 145+ anggota, kalebu ndhukung tech talk saben wulan."],
  cv: ["You can view and download Zainal's English CV using the 'View CV' button on the homepage.", "CV Zainal bisa dilihat dan diunduh melalui tombol 'View CV' di halaman utama website ini.", "CV Zainal basa Inggris bisa dideleng lan diunduh liwat tombol 'Deleng CV' ing kaca ngarep situs iki."],
  contact: ["Contact Zainal via LinkedIn linkedin.com/in/zaiinhs, GitHub github.com/zaiinhs or email zainalabidinhsc@gmail.com.", "Kamu bisa menghubungi Zainal melalui LinkedIn linkedin.com/in/zaiinhs, GitHub github.com/zaiinhs, atau email zainalabidinhsc@gmail.com.", "Kowe bisa ngubungi Zainal liwat LinkedIn linkedin.com/in/zaiinhs, GitHub github.com/zaiinhs, utawa email zainalabidinhsc@gmail.com."],
  articles: ["Read Zainal's articles on this site, including discussions of Data Analyst/Engineer/Scientist roles, web development and other technical topics.", "Zainal menulis artikel di website ini. Buka menu Articles untuk membaca tulisannya, termasuk pembahasan tentang peran Data Analyst/Engineer/Scientist, web development, dan topik teknologi lain.", "Zainal nulis artikel ing situs iki. Deleng menu Artikel kanggo maca tulisane, kalebu babagan peran Data Analyst/Engineer/Scientist, web development, lan topik teknologi liyane."],
  career: ["Zainal focuses on Technical Product Specialist work combining product delivery, data solutions, client implementation and engineering coordination. His hands-on experience includes Python, SQL, REST APIs, React/Next.js, Docker, Linux/VM and UAT. Reach out through LinkedIn or email on this site.", "Zainal menargetkan peran Technical Product Specialist yang menggabungkan product delivery, solusi data, implementasi klien, dan koordinasi engineering. Ia membawa pengalaman langsung dengan Python, SQL, REST API, React/Next.js, Docker, Linux/VM, dan UAT. Hubungi melalui LinkedIn atau email yang tercantum di website.", "Zainal fokus ing peran Technical Product Specialist sing nggabungake pangiriman produk, solusi data, implementasi klien, lan koordinasi engineering. Pengalaman langsung kalebu Python, SQL, REST API, React/Next.js, Docker, Linux/VM, lan UAT. Hubungi liwat LinkedIn utawa email ing situs iki."],
  fallback: ["I'm a static profile assistant for Zainal Abidin, not a connected AI model or API. Ask about his role, product and data experience, client implementation, skills, projects, CV, community or contact details.", "Aku adalah asisten profil statis tentang Zainal Abidin dan belum terhubung ke model AI/API. Coba tanyakan tentang peran, pengalaman produk dan data, implementasi klien, skill, proyek, CV, komunitas, atau kontaknya.", "Aku asisten profil statis Zainal Abidin, durung nyambung menyang model AI/API. Takona babagan peran, pengalaman produk lan data, implementasi klien, skill, proyek, CV, komunitas, utawa kontak."],
} as const;

export type ChatIntent = keyof typeof replies;

export function chatReply(intent: ChatIntent, locale: Locale): string {
  const index = locale === "en" ? 0 : locale === "id" ? 1 : 2;
  return replies[intent][index];
}
